baseURL: "https://heissanjay.github.io/"
title: "heissanjay"

menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "blog"
      name: "Blog"
      url: "/posts"
      weight: 2
    - identifier: "about"
      name: "About"
      url: "/about"
      weight: 3
    - identifier: "contact"
      name: "Contact"
      url: "/contact"
      weight: 4

params:
  bannerText:
    greetings: "Hey ThereðŸ‘‹, à®µà®£à®•à¯à®•à®®à¯ (Vanakkam). "
    introduction: "This is Sanjay, mostly I prefer \"heissanjay\" as my username on the internet."
    description: >
      I'm a Software Engineer and I usually deal with things at the Infrastructure and Operation levels.
      I'm currently working on <span class="underline">building Machine Learning pipelines in AWS SageMaker</span>.I'm interested in Machine Learning, NLP, Generative AI etc.